# -*- coding: utf-8 -*-
"""Python-basic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eisBG_jK5DNSGnQkXkfpiEotXNB29lOe
"""



"""Write a Python program to print “Hello World!”"""

print  ("Hello World!")

"""Write a Python program to create two variables, assign integer values to them and add them using the “+” operator to store the result in another variable and print it. Input Format:You do not need to read any input in this problem.Sample Output:

"""

a=10
b=20
c=a+b
print ("Result of addition is:", c)

Write a Python program to create two variables, assign random values to them
and add them using the “+” operator to store the result in another variable and
print it.

a="edureka!"
b=" 10"
c=a+b
print (c)

